# Generated by Powerlevel10k configuration wizard.
# Based on romkatv/powerlevel10k configuration.
# Custom configuration for the format: [full-path] ([branchname]) [command input here]

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
  )

  # The list of segments shown on the right. Fill it with less important segments.
  # Right prompt on the last prompt line (where you are typing) is empty by default.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

  # Basic style options that define the overall look of your prompt.
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no line between different-color segments
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=           # no segment icons

  # Current directory.
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=012
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_absolute_chars
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=9999  # show full path
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  # Don't shorten path in /home/username
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER=
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  # Format: [full-path]
  typeset -g POWERLEVEL9K_DIR_PREFIX='['
  typeset -g POWERLEVEL9K_DIR_SUFFIX=']'

  # Git status.
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON=
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON=
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON=
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON=
  # Format: ([branchname])
  typeset -g POWERLEVEL9K_VCS_PREFIX='('
  typeset -g POWERLEVEL9K_VCS_SUFFIX=')'
  typeset -g POWERLEVEL9K_VCS_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=076

  # Disable default formatting for git status indicators
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=076
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=076
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=076

  # Add a space after the prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '

  # Instant prompt mode.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload gives you a live preview of changes to ~/.p10k.zsh.
  typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'